/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ankkajahti;

import java.awt.event.ActionListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.LinkedList;
import javax.swing.Timer;

/**
 *
 * @author jphanski
 */
public class Ikkuna extends javax.swing.JPanel implements ActionListener {
    LinkedList<Ankka> ankat;
    public int fps;
    private Timer timer;
    /**
     * Creates new form Ikkuna
     */
    public Ikkuna(LinkedList<Ankka> ankat) {
        initComponents();
        this.ankat = ankat;
        fps = 0;
        
        timer = new Timer(1000/Ankkajahti.ticks, this);
        timer.start(); 
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setColor(Color.cyan);
        g2d.fillRect(0, 0, this.getWidth(), this.getHeight());
        for (Ankka a : ankat) {
            piirraAnkka(g2d, a.getX(), a.getY());
        }
        g2d.setColor(Color.BLUE);
        g2d.fillRect(0, (int) (this.getHeight() * 0.75), this.getWidth(), this.getHeight());
    }
    
    /*@Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        g2d.setColor(Color.BLACK);
        g2d.fillRect(0, 0, this.getWidth(), this.getHeight());
        for (Ankka a : ankat) {
            piirraAnkka(g2d, a.getX(), a.getY());
        }
    }*/
    protected void piirraAnkka(Graphics2D g2d, double x, double y) {
        g2d.setColor(Color.YELLOW);
        g2d.fillRoundRect((int) (x * this.getWidth()), (int) (y * this.getHeight()), 20, 20, 6, 6);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e) {
        this.repaint();
        Toolkit.getDefaultToolkit().sync();
        fps++;
        timer.restart();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
